server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001       #匹配后提供服务的路由地址
          uri: lb://cloud-provider-payment #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/**         # 断言，如果提供的服务下面有这个路径，才会进行路由
                                            # 同时这个路径，也是网关可以访问的路径
#        - id: payment_routh2 #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
##            uri: http://localhost:8001      #匹配后提供服务的路由地址
#            uri: lb://cloud-provider-payment #匹配后提供服务的路由地址
#            predicates:
#              - Path=/payment/discover/**         # 断言，路径相匹配的进行路由
#        - id: payment-routh2
#            uri: http://localhost:8001
#            predicates:
#              - Path=/payment/discover/**

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
